### PR TITLE
Allow PHP8

### PR DESCRIPTION
**Pull request by Jurigag**

### CODE REVIEW

**Comment by Jurigag** [comment]
Travis seems to be stuck, i run tests locally and there is no problem with PHP8 @matthiasnoback

**Comment by matthiasnoback** [comment]
I was planning to look into this some day soon, because it should also support native PHP 7.4 type hints instead of just doc blocks. I'll make it work with PHP 8 as well then. Hoping to do this within a couple of weeks.

**Comment by Jurigag** [comment]
Cool, yea it's kind of annoying that you need to add phpdocs, well wanted to just add php8 on composer because it blocks us currently from upgrading to php8.

**Comment by matthiasnoback** [comment]
I've finished the work and released v0.11.0. Since this is a new feature, I'm interested to learn if it works for your project.

**Pull request closed without merging**
